apiVersion: v1
kind: Namespace
metadata:
  name: k8s-edu-ondemand-hashtag
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edu
  namespace: k8s-edu-ondemand-hashtag
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: edu
  namespace: k8s-edu-ondemand-hashtag
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edu
subjects:
  - kind: ServiceAccount
    name: edu
    namespace: k8s-edu-ondemand-hashtag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi-deployment
  namespace: k8s-edu-ondemand-hashtag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-fastapi-pod
  template:
    metadata:
      labels:
        app: python-fastapi-pod
    spec:
      serviceAccountName: edu
      containers:
      - name: agent-python-fastapi
        image: whatap/agent-python-fastapi
        ports:
        - name: fastapi-port
          containerPort: 8000
        env:
          - name: WHATAP_SERVER_HOST
            value: {WHATAP_SERVER_HOST}
          - name: WHATAP_LICENSE
            value: {WHATAP_LICENSE}
          - name: WHATAP_APP_NAME
            value: {WHATAP_APP_NAME}
          - name: WHATAP_LOGGING_ENABLED
            value: {WHATAP_LOGGING_ENABLED}
          - name: NODE_IP
            valueFrom: { fieldRef: { fieldPath: status.hostIP } }
          - name: NODE_NAME
            valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          - name: POD_NAME
            valueFrom: { fieldRef: { fieldPath: metadata.name } }
---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-edu-ondemand-hashtag
  name: python-fastapi-service
spec:
  selector:
    app: python-fastapi-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: fastapi-port
  type: NodePort
