apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-fastapi-pod
  template:
    metadata:
      labels:
        app: python-fastapi-pod
    spec:
      containers:
      - name: agent-python-fastapi
        image: whatap/agent-python-fastapi
        ports:
        - name: fastapi-port
          containerPort: 8000
        env:
          - name: WHATAP_SERVER_HOST
            value: {WHATAP_SERVER_HOST}
          - name: WHATAP_LICENSE
            value: {WHATAP_LICENSE}
          - name: WHATAP_APP_NAME
            value: {WHATAP_APP_NAME}
          - name: WHATAP_LOGGING_ENABLED
            value: {WHATAP_LOGGING_ENABLED}
          - name: NODE_IP
            valueFrom: { fieldRef: { fieldPath: status.hostIP } }
          - name: NODE_NAME
            valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          - name: POD_NAME
            valueFrom: { fieldRef: { fieldPath: metadata.name } }

---
apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-service
spec:
  selector:
    app: python-fastapi-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: fastapi-port
  type: NodePort
