apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-fastapi-pod
  template:
    metadata:
      labels:
        app: python-fastapi-pod
    spec:
      containers:
      - name: agent-python-fastapi
        image: whatap/b_fastapi:latest
        ports:
        - name: fastapi-port
          containerPort: 8000
        resources:
          limits:
            cpu:
              100m
            memory:
              100Mi
        env:
        - name: license
          value: "x41pl22ek7jhv-z43cebasdv4il7-z62p3l35fj5502"
        - name: whatap_server_host
          value: "15.165.146.117"
        - name: app_name
          value: "JOB-TRIGGER"
        - name: app_process_name
          value: "uvicorn"
        - name: NODE_IP
          valueFrom: { fieldRef: { fieldPath: status.hostIP } }
        - name: NODE_NAME
          valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
        - name: POD_NAME
          valueFrom: { fieldRef: { fieldPath: metadata.name } }
---
apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-service
spec:
  selector:
    app: python-fastapi-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: fastapi-port
  type: NodePort
