# WHATAP GUIDE DOCUMENTS
# https://www.whatap.io/document/guide/WHATAP_PYTHON_GETTING_STARTED.pdf
# https://www.whatap.io/document/guide/WHATAP_PYTHON_INSTALL_GUIDE.pdf
# https://www.whatap.io/document/guide/WHATAP_PYTHON_CONFIGURATION_GUIDE.pdf

license=x42eg202960vn-x1hpafehq08daj-z1pmhm6acaktut
whatap.server.host=15.165.146.117

# application name
app_name=django-celery-2

# middleware process name ex)uwsgi, gunicorn ..
app_process_name=python

logsink_enabled=true
logsink_trace_enabled=true
trace_logging_enabled=true

whatap.okind=NUT
whatap.onode=SH
net_udp_port=6600
OID=-839985378
profile_basetime=0
