apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-fastapi-pod
  template:
    metadata:
      labels:
        app: python-fastapi-pod
    spec:
      containers:
      - name: agent-python-fastapi
        image: registry.whatap.io:5000/demo-petclinic-deploy-python
        ports:
        - name: fastapi-port
          containerPort: 8000
        env:
        - name: license
          value: x41pl22ek7jhv-z43cebasdv4il7-z62p3l35fj5502
        - name: whatap_server_host
          value: 15.165.146.117
        - name: app_name
          value: python-demo
        - name: app_process_name
          value: gunicorn
        - name: whatap.okind
          value: "test"
        - name: NODE_IP
          valueFrom: { fieldRef: { fieldPath: status.hostIP } }
        - name: NODE_NAME
          valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
        - name: POD_NAME
          valueFrom: { fieldRef: { fieldPath: metadata.name } }
---
apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-service
spec:
  selector:
    app: python-fastapi-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: fastapi-port
  type: NodePort
