apiVersion: batch/v1
kind: Job
metadata:
  name: python-method-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: agent-python-method
        image: whatap/agent-python-method:0.1.1
        volumeMounts:
        - name: shared-data
          mountPath: /app/share
        env:
          - name: HASHTAG
            value: {HASHTAG}
          - name: WHATAP_LICENSE
            value: {WHATAP_LICENSE}
          - name: WHATAP_LOGGING_ENABLED
            value: {WHATAP_LOGGING_ENABLED}
          - name: NODE_IP
            valueFrom: { fieldRef: { fieldPath: status.hostIP } }
          - name: NODE_NAME
            valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          - name: POD_NAME
            valueFrom: { fieldRef: { fieldPath: metadata.name } }
      volumes:
      - name: shared-data
        hostPath:
          path: /home/ec2-user/jykim_local/share