apiVersion: batch/v1
kind: Job
metadata:
  name: python-method-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: agent-python-method
        image: whatap/agent-python-method:latest
        env:
          - name: HASHTAG
            value: {HASHTAG}
          - name: license
            value: {license}
          - name: whatap_server_host
            value: {whatap_server_host}
          - name: app_name
            value: {app_name}
          - name: app_process_name
            value: {app_process_name}
          - name: NODE_IP
            valueFrom: { fieldRef: { fieldPath: status.hostIP } }
          - name: NODE_NAME
            valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          - name: POD_NAME
            valueFrom: { fieldRef: { fieldPath: metadata.name } }