apiVersion: batch/v1
kind: Job
metadata:
  name: python-method-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: agent-python-method
        image: whatap/agent-python-method:latest
        env:
          - name: HASHTAG
            value: {HASHTAG}
          - name: WHATAP_LICENSE
            value: {WHATAP_LICENSE}
          - name: WHATAP_SERVER_HOST
            value: {WHATAP_SERVER_HOST}
          - name: WHATAP_APP_NAME
            value: {WHATAP_APP_NAME}
          - name: WHATAP_LOGGING_ENABLED
            value: {WHATAP_LOGGING_ENABLED}
          - name: NODE_IP
            valueFrom: { fieldRef: { fieldPath: status.hostIP } }
          - name: NODE_NAME
            valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          - name: POD_NAME
            valueFrom: { fieldRef: { fieldPath: metadata.name } }